# Generated by Django 4.0 on 2025-07-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalili', models.TextField()),
                ('ugonjwa', models.CharField(max_length=255)),
                ('vipimo', models.TextField(blank=True, null=True)),
                ('tiba', models.TextField(blank=True, null=True)),
                ('kinga', models.TextField(blank=True, null=True)),
                ('ushauri', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
