# Generated by Django 4.2 on 2025-07-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorreport',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='doctorreport',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='DoctorReport',
        ),
    ]
