# Generated by Django 4.2 on 2025-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(choices=[(True, 'Confirmed'), (False, 'Not Confirmed')], default=False),
        ),
    ]
