# Generated by Django 4.2 on 2025-07-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Doctor', 'Doctor'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
