# Generated by Django 4.2 on 2025-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
