# Generated by Django 4.2 on 2025-07-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_chatsession_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
    ]
