# Generated by Django 4.2 on 2025-07-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_remove_chatsession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='session',
        ),
        migrations.RemoveField(
            model_name='predicteddisease',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PredictedDisease',
        ),
    ]
