# Generated by Django 4.2 on 2025-07-28 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, null=True, size=None),
        ),
    ]
