# Generated by Django 4.2 on 2025-07-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_chatsession_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='confirmed_diseases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='eliminated_diseases',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_questions',
            field=models.JSONField(default=list),
        ),
    ]
