# Generated by Django 4.2 on 2025-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
