# Generated by Django 4.2 on 2025-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0012_remove_medicalreport_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
