# Generated by Django 4.2 on 2025-08-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0013_chatsession_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='advice',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
