# Generated by Django 4.2 on 2025-07-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
